name: liplibrary
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^5.1.6
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.0.6
  permission_handler: ^3.2.2
  unicorndial: ^1.1.5
  location: ^2.3.5
  android_intent: ^0.3.3+2
  shared_preferences: ^0.5.3+4
  path_provider: ^1.3.0
  flutter_google_places: ^0.2.3
  intl: ^0.16.0
  http: ^0.12.0+2
  google_maps_flutter: ^0.5.21+6
  google_maps_webservice: ^0.0.15
  autocomplete_textfield: ^1.6.6
  mongodb_mobile: ^0.0.7
  camera: ^0.5.4+3
  path: ^1.6.4
  video_player: ^0.10.2+1
  cached_network_image: ^1.1.1
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
